---
on:
  push: {}

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v3

      - name: setup
        run: pip3 install pre-commit

      - name: run pre-commit
        run: pre-commit run --show-diff-on-failure --all-files
        env:
          SKIP: "no-commit-to-branch"
